; 練習問題 2.92: 変数に順番をつけることによって、異なる変数の
; 多項式同⼠の加算と乗算が動作するよう多項式パッケージを拡張
; せよ。(これは簡単ではない!)
(define (add-poly p1 p2)
  (cond ((variable>? (variable p1) (variable p2))
         (make-poly (variable p1)
                    (add-terms (term-list p1)
                               (term-list p2)))
         ((variable>? (variable p2) (variable p1))
          (make-poly (variable p2)
                     (add-terms (term-list p2)
                                (term-list p1)))
         (else
          (make-poly (variable p1)
                     (add-terms (term-list p1)
                                (term-list p2))))))))
(define (mul-poly p1 p2)
    (cond ((variable>? (variable p1) (variable p2))
             (make-poly (variable p1)
                        (mul-terms (term-list p1)
                                 (term-list p2)))
             ((variable>? (variable p2) (variable p1))
            (make-poly (variable p2)
                         (mul-terms (term-list p2)
                                    (term-list p1)))
             (else
            (make-poly (variable p1)
                         (mul-terms (term-list p1)
                                    (term-list p2))))))))
